### ISSUE TITLE
new 'display'-component Calendar

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#57] opened 2018-03-13 14:21 UTC
a new child-element for 'display' -> calendar

calendar should show data from the tableau as visible information.

**Comment by dzhwmeisner** [comment] 2018-04-12 12:45
basic implementation done, need to be tested http://vmtest.dzhw.local:8080/devhtml5/page14.html

**Comment by FineCordua** [comment] 2018-04-13 08:47
- Years are missing in large scale
- Monthnames are too long, overwrite eachother in smaller scales
- Year 2017 seems to be not available in large scale but depicted in small scale

**Comment by andreaschu** [comment] 2018-04-17 16:00
A.  indicate colour of episode type as coloured bar instead of coloured text 
B.  only one type of episode per line?
C.  hight of line: 1. at least the hight of a readable year number (in desktop view) and 2. the hight of the maximum of parallel episodes (for all years)
D.  space between episode bars possible?

**Comment by kastirke** [comment] 2018-04-30 12:37
[E] Episodes are wrongly numbered. It should be start=1=january (not start=1=february), or?
[F] "data-meta-color-grade" is invariant (only exception is the second "Studium" episode). Is this correct?
[G] Different episodes of the same item are displayed using different colors, right? Unfortunately, the colors don't fit to the legend anymore. :(
[H] May you create a more realistic role/person. This one was very busy and therefore the calender looks overloaded. 

![grafik](https://user-images.githubusercontent.com/30147532/39426478-4e88b080-4c80-11e8-81fb-73312ce9f8c0.png)
![grafik](https://user-images.githubusercontent.com/30147532/39426644-eaa00dc4-4c80-11e8-88a6-21722005915a.png)
![grafik](https://user-images.githubusercontent.com/30147532/39427436-febf659a-4c83-11e8-979e-e867e4415d96.png)

**Comment by kastirke** [comment] 2018-04-30 12:48
Stopped further testing with iPhone SE and wait for new development. :)

**Comment by dzhwmeisner** [comment] 2018-06-07 09:42
call for test

    Years are missing in large scale
[CM] fixed

    Monthnames are too long, overwrite eachother in smaller scales
[CM] fixed. Will be reduced in smaller scales

    Year 2017 seems to be not available in large scale but depicted in small scale
[CM] cannot be reproduced


A. indicate colour of episode type as coloured bar instead of coloured text
[CM] fixed

B. only one type of episode per line?
[CM] fixed

C. height of line: 1. at least the hight of a readable year number (in desktop view) and 2. the height of the maximum of parallel episodes (for all years)
[CM] fixed

D. space between episode bars possible?
[CM] fixed

[E] Episodes are wrongly numbered. It should be start=1=january (not start=1=february), or?
[CM] Metadata are dummy-data so far. It's a technical nummeration starting with 0 instead of 1

[F] "data-meta-color-grade" is invariant (only exception is the second "Studium" episode). Is this correct?
[CM] removed. Not needed anymore. Was used only where needed.

[G] Different episodes of the same item are displayed using different colors, right? Unfortunately, the colors don't fit to the legend anymore. :(
[CM] removed. following Episodes use different slot

**Comment by Miktarbad** [comment] 2018-06-18 11:36
page14 is unavailable on desktop?

[H] Monthnames:
- got better, but they still move over the others


![screenshot_2018-06-18_page14](https://user-images.githubusercontent.com/29864065/41533870-954554c2-72fc-11e8-8b70-5d73de949a26.png)

**Comment by andreaschu** [comment] 2021-07-05 14:24
I close this issue because of the calendar refinement. Can be opened again, when it will be used again.

**Closed by andreaschu** 2021-07-05 14:24 UTC
Labels: 1, category: zofar, prio: 2, status: testing, type: backlog.task
